# Generated by Django 4.2.7 on 2023-11-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stage', models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advance', 'Advance')], max_length=10)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000)),
                ('prof_img', models.ImageField(blank=True, default='profile_default_icon.png', null=True, upload_to='profil_pic')),
                ('cover_img', models.ImageField(blank=True, null=True, upload_to='cover_pic')),
                ('details', models.TextField(blank=True, null=True)),
                ('link', models.URLField()),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=40)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('projects_name', models.CharField(blank=True, max_length=20, null=True)),
                ('project_short_details', models.TextField(blank=True, null=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_name', models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('Diploma', 'Diploma'), ('BSC', 'BSC'), ('Other', 'Other')], max_length=25)),
                ('institute_name', models.CharField(max_length=200)),
                ('ins_address', models.TextField(blank=True, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
    ]
