# Generated by Django 4.2.7 on 2023-11-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0004_delete_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cover_img',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='prof_img',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/cover_pic/'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, default='default/default_portfoli_image', null=True, upload_to='portfolio/profil_pic/'),
        ),
    ]
