# Generated by Django 4.2.7 on 2023-11-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_team_about_us_team_blog_slide_team_setting_config_and_more'),
        ('personal_profile', '0005_remove_portfolio_cover_img_remove_portfolio_prof_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Web_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
    ]
