# Generated by Django 4.2.7 on 2023-11-18 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_team_about_us_team_blog_slide_team_setting_config_and_more'),
        ('personal_profile', '0006_web_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='ins_address',
            new_name='institute_address',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='project_short_details',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='education',
            name='duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('institute_name', models.CharField(max_length=200)),
                ('institute_address', models.TextField(blank=True, null=True)),
                ('starting_date', models.DateField(blank=True, null=True)),
                ('ending_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('details_description', models.TextField(blank=True, null=True)),
                ('resume_description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('address_district', models.CharField(blank=True, max_length=20, null=True)),
                ('address_country', models.CharField(default='Bangladesh', max_length=30)),
                ('clients', models.PositiveIntegerField(blank=True, null=True)),
                ('projects', models.PositiveIntegerField(blank=True, null=True)),
                ('awards', models.PositiveIntegerField(blank=True, null=True)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
    ]
