# Generated by Django 4.2.7 on 2023-11-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_team_about_us_team_blog_slide_team_setting_config_and_more'),
        ('personal_profile', '0007_rename_ins_address_education_institute_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=300, null=True)),
                ('person_image', models.ImageField(blank=True, default='default/personal_profile_tetimonial_icon.png', null=True, upload_to='team_member/testimonials/')),
                ('person_designation', models.CharField(blank=True, max_length=300, null=True)),
                ('opinion', models.TextField(blank=True, null=True)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.team_member')),
            ],
        ),
    ]
