# Generated by Django 4.2.7 on 2023-11-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_team_about_us_team_blog_slide_team_setting_config_and_more'),
        ('personal_profile', '0008_team_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_testimonials',
            new_name='Testimonials',
        ),
    ]
