# Generated by Django 4.2.7 on 2023-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0009_rename_team_testimonials_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
