# Generated by Django 4.2.7 on 2023-11-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0010_education_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='testimonials_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
