# Generated by Django 4.2.7 on 2023-11-19 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0011_about_me_testimonials_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_profile.portfolio_category'),
        ),
    ]
