# Generated by Django 4.2.7 on 2023-11-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0012_portfolio_category_portfolio_portfolio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.ImageField(blank=True, default='default/default_portfoli_image.jpg', null=True, upload_to='portfolio/profil_pic/'),
        ),
    ]
