# Generated by Django 4.2.7 on 2023-11-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0013_alter_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
