# Generated by Django 4.2.7 on 2023-11-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0014_portfolio_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
