# Generated by Django 4.2.7 on 2023-11-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0015_testimonials_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_complete',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
