# Generated by Django 4.2.7 on 2023-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0016_education_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='is_complete',
            field=models.BooleanField(default=True),
        ),
    ]
