# Generated by Django 4.2.7 on 2023-11-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0018_remove_experience_projects_name_experience_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_me',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
