# Generated by Django 4.2.7 on 2023-11-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_profile', '0019_about_me_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_me',
            name='hours',
        ),
    ]
