# Generated by Django 4.2.7 on 2023-11-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=200)),
                ('image', models.ImageField(upload_to='team_member/prof/')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('address_district', models.CharField(blank=True, max_length=20, null=True)),
                ('address_country', models.CharField(default='Bangladesh', max_length=30)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
