# Generated by Django 4.2.7 on 2023-11-17 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_is_admin_user_is_team_member_delete_team_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_member/prof/')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_upazila', models.CharField(blank=True, max_length=20, null=True)),
                ('address_district', models.CharField(blank=True, max_length=20, null=True)),
                ('address_country', models.CharField(default='Bangladesh', max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('home.user',),
        ),
    ]
