# Generated by Django 4.2.7 on 2023-11-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_team_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['joined_date']},
        ),
    ]
