# Generated by Django 4.2.7 on 2023-11-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_skills_team_member_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='stage',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=10),
        ),
    ]
