# Generated by Django 4.2.7 on 2023-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_skills_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='stage',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Medium', 'Medium'), ('Advanced', 'Advanced')], max_length=10, null=True),
        ),
    ]
