# Generated by Django 4.2.7 on 2023-11-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_web_site_google_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_site',
            name='google_map',
        ),
    ]
