# Generated by Django 4.2.7 on 2023-11-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_team_about_us_team_blog_slide_team_setting_config_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='team_member',
            name='address_upazila',
        ),
    ]
