# Generated by Django 4.2.7 on 2023-11-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_team_member_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_setting_config',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
