# Generated by Django 4.2.7 on 2023-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_team_setting_config_setting_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_about_us',
            name='team_phone_number',
        ),
        migrations.AddField(
            model_name='team_setting_config',
            name='team_phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
