# Generated by Django 4.2.7 on 2023-11-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_team_about_us_team_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_setting_config',
            name='team_designation',
            field=models.CharField(blank=True, default='default/pyteam-c-icon.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team_setting_config',
            name='team_logo',
            field=models.ImageField(blank=True, default='default/team-c-logo-transparent.png', null=True, upload_to='team/'),
        ),
    ]
