# Generated by Django 4.2.7 on 2023-11-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_team_setting_config_team_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_blog_slide',
            name='slide_image',
            field=models.ImageField(blank=True, default='default/slider_bg.jpg', null=True, upload_to='team/'),
        ),
    ]
