# Generated by Django 4.2.7 on 2023-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_team_blog_slide_slide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='home.skills'),
        ),
    ]
