# Generated by Django 4.2.7 on 2023-11-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_team_member_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='skills',
            field=models.ManyToManyField(blank=True, to='home.skills'),
        ),
    ]
